In [1]:
import numpy as np

In [6]:
a = np.arange(16).reshape((2,2,2,2))
print(a)

print('-------')
aa = np.reshape(a, (a.shape[0]*a.shape[1], -1))
print(aa)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
-------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
b = np.ones(a.shape)
print(b)

In [ ]:
b[a<3] = 0
print(b)

In [ ]:
print(a * b)

In [ ]:
a[1] = -1
# print(np.maximum(a, 0))
print(a>0)

In [ ]:
print(a>2)
print(b)
print((a>2)*b)

In [ ]:
print(np.zeros((3,)))

In [ ]:
for i in xrange(4):
    print('k'+str(i))

In [ ]:
q = np.random.randn(2,3)
print(q)

In [ ]:
print(np.prod(4,5,6))