In [1]:
import numpy as np

In [2]:
a = np.arange(8).reshape((2,4))
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [3]:
b = np.ones(a.shape)
print(b)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [4]:
b[a<3] = 0
print(b)

[[ 0.  0.  0.  1.]
 [ 1.  1.  1.  1.]]


In [5]:
print(a * b)

[[ 0.  0.  0.  3.]
 [ 4.  5.  6.  7.]]


In [6]:
a[1] = -1
# print(np.maximum(a, 0))
print(a>0)

[[False  True  True  True]
 [False False False False]]


In [7]:
print((a>2)*b)

[[ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]]


In [8]:
print(np.zeros((3,)))

[ 0.  0.  0.]


In [11]:
for i in xrange(4):
    print('k'+str(i))

k0
k1
k2
k3


In [16]:
q = np.random.randn(2,3)
print(q)

[[-1.65041799  1.00167467  0.06855983]
 [ 1.99676453  0.49905392  0.31044431]]


In [17]:
print(np.prod(4,5,6))

TypeError: data type not understood