In [1]:
import numpy as np

In [2]:
a = np.arange(8).reshape((2,4))
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [8]:
b = np.max(a, axis=1).reshape((2, -1))
print(b)

print(np.max(a))

print(np.maximum(a, 2))

[[3]
 [7]]
7
[[2 2 2 3]
 [4 5 6 7]]


In [9]:
c = a - b
print(c)

[[-3 -2 -1  0]
 [-3 -2 -1  0]]


In [16]:
d = [2, 1]
print(a[range(2), d].reshape((2,-1)))

[[2]
 [5]]


In [11]:
e = np.sum(d, axis=1)
print(e)

[ 14 126]


In [12]:
y = [1, 2]
aa = d[range(2), y].reshape((2,-1))
print(aa)

[[ 1]
 [36]]


In [13]:
print(d/aa)

[[0 1 4 9]
 [0 0 1 1]]


In [21]:
print(np.logspace(-4, 2, 7))
print(np.logspace(-3, 2, 6))

[  1.00000000e-04   1.00000000e-03   1.00000000e-02   1.00000000e-01
   1.00000000e+00   1.00000000e+01   1.00000000e+02]
[  1.00000000e-03   1.00000000e-02   1.00000000e-01   1.00000000e+00
   1.00000000e+01   1.00000000e+02]


ffs